### PR TITLE
Upgrade demo-app to superforms 2, sveltekit 2, and vite 5

### PR DESCRIPTION
**Pull request by ptmkenny**
This builds on top of https://github.com/Tommertom/svelte-ionic-app/pull/102.

It adds superforms 2 support as described in https://github.com/Tommertom/svelte-ionic-app/issues/103 and also upgrades to sveltekit 2, vite 5.

As far as I can tell, it's working, but I just started using superforms today so it's very likely I missed something.

I followed the official migration guide: https://superforms.rocks/migration-v2

### CODE REVIEW

**Comment by ptmkenny** [comment]
Actually the Inputs form needs some more work: the alert message is never shown.  This is not a problem related to superforms v2; it can be seen on the production app as well, so I'll open a new issue.

**Comment by ptmkenny** [comment]
Issue with alerts: https://github.com/Tommertom/svelte-ionic-app/issues/105

**Comment by Tommertom** [comment]
Hi there - I will accept this PR as it is great you help keeping up with versions.

For other features to make it more like how it should be - do yo think superforms is the best bet so far? If so, then it makes sense adding some "best practices" to it

**Comment by gerhardcit** [comment]
Having tried superforms recently and then removed it again, I would not want superforms to be "built in" please?
Superforms is great, don't get me wrong, but if you ant to get very specific and more SPA based for mobile devices, I'm not sure it has to be build in.

Superforms is great for login and registration maybe (that's what I found) but when when you get to date to more admin like backoffice forms, it's get's messy and you have to bend your data to suite the forms.
But ionic is not suppose to be a backoffice obviously. 
I still think superforms is an "opt in" after spending a week using it and then removing it when it went beyond the basics form completion.

**Comment by Tommertom** [comment]
> Having tried superforms recently and then removed it again, I would not want superforms to be "built in" please?
> Superforms is great, don't get me wrong, but if you ant to get very specific and more SPA based for mobile devices, I'm not sure it has to be build in.

I agree it should not be built in the ionic-svelte package. So I wont do that. In the demo app it is just a way to show how forms can be handled knowing that the kit-way (form actions) won't work in SPA. 

So with that caveat in mind, and as typically seen in SPA, the front end does need to do some validation before subitting to the backend. And that is actually good UI imho, as if you keep all form validation in the backend, then you need to do a roundtrip to the server before you can suggest the user.

At least, as far as I understand forms :)

To conclude - no superforms in ionic-svelte, but some sort of form handling in the demo app should not be a problem - but I am not really motivated to go all the way.

**Pull request merged**
