### PR TITLE
fix: build broke after npm run dev

### PR DESCRIPTION
**Pull request by jakobrosenberg**

### CODE REVIEW

**Comment by Tommertom** [comment]
ok - btw, I reckon spank is a devDependency, not dependency.. Will fix that one.

**Comment by Tommertom** [comment]
Just checking @jakobrosenberg  - things seem to work better, but my vscode now complaining - 

image

Any clues was has happened - this occurred right after the merge into master and appeared only later. SSR build and Client build work perfectly though.

**Comment by Tommertom** [comment]
By the way, I love the new integration with the hooks - so happy with the upgrade so far :)

**Comment by jakobrosenberg** [comment]
The options aren't yet typed in ts or jsdoc. You can fix them with a `// @ts-ignore` for now.

**Comment by Tommertom** [comment]
Works like a charm - thx!

**Pull request merged**
